---
root: true
parser: 'babel-eslint'
env:
  commonjs: true
  browser: true
  node: true
  es6: true
extends:
  - standard
  - eslint:recommended
  - plugin:node/recommended
plugins:
  - node
  - html
rules: {}
globals:
  jQuery: true
  moment: true
  Cookies: true
  _: true
